### ISSUE TITLE
Case of JSON key parameters is different in GET versus PUT/POST requests

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#48]
On making a GET request, StreamingBandit currently returns camelCase JSON keys, for example, "getAction".

Whereas if you PUT or POST, you need to send the same keys in lowercase, for example, "getaction".

It would both be easier to process the data and more consistent if we'd equalize the naming convention for the keys in all HTTP methods.

![put](https://user-images.githubusercontent.com/95014/30735156-39d9affe-9f7e-11e7-94b6-cc3044db5000.png)

![get](https://user-images.githubusercontent.com/95014/30735157-39e0b6f0-9f7e-11e7-9251-8a786bcf34e3.png)

**Comment by g0ulash** [comment]
What would you say is the most convenient way? I think the most pythonic way would be to convert everything to snake_case instead of camelCase? So getAction becomes get_action (is also more consistent with the use of e.g., user_id, delta_days).

**Comment by MKaptein** [comment]
Yes, I guess Jules is right:

Naming Convention

"Internal" means internal to a module or protected or private within a class.
Prepending a single underscore (_) has some support for protecting module variables and functions (not included with import * from). Prepending a double underscore (__) to an instance variable or method effectively serves to make the variable or method private to its class (using name mangling).
Place related classes and top-level functions together in a module. Unlike Java, there is no need to limit yourself to one class per module.
Use CapWords for class names, but lower_with_under.py for module names. Although there are many existing modules named CapWords.py, this is now discouraged because it's confusing when the module happens to be named after a class. ("wait -- did I write import StringIO or from StringIO import StringIO?")

Guidelines derived from Guido's Recommendations

Type	Public	Internal
Packages	lower_with_under	
Modules	lower_with_under	_lower_with_under
Classes	CapWords	_CapWords
Exceptions	CapWords	
Functions	lower_with_under()	_lower_with_under()
Global/Class Constants	CAPS_WITH_UNDER	_CAPS_WITH_UNDER
Global/Class Variables	lower_with_under	_lower_with_under
Instance Variables	lower_with_under	_lower_with_under (protected) or __lower_with_under (private)
Method Names	lower_with_under()	_lower_with_under() (protected) or __lower_with_under() (private)
Function/Method Parameters	lower_with_under	
Local Variables	lower_with_under



https://google.github.io/styleguide/pyguide.html <https://google.github.io/styleguide/pyguide.html>

Lets adopt that.

**Comment by robinvanemden** [comment]
I agree!

**Comment by MKaptein** [comment]
Hi,

Yes! This actually is / was issue #33 I would say. 

@Jules, could you please check this once more, I also need it for the paper writing.
@Robin, instead of “equalize naming convention” I would suggest: “they should all be lowercase”.

Thanks.

**Comment by MKaptein** [comment]
Ow, apparently these things arrive in arbitrary order :S The google style guide was send after sending the message above.

**Comment by g0ulash** [comment]
I will try to fix this today. This can take a little while, since this naming convention has been quite engrained in the software (have to check every piece of code for camelCases and change it to snake_case) including the documentation. I will change every camelCase to snake_case then.

**Comment by MKaptein** [comment]
No idea which editor you are using, but there are a number that provide good refactoring support. 

I am going to assume snake_case in the paper; is that ok?

**Comment by g0ulash** [comment]
It will for example also affect the Summary call, but I'll just have to check which variables are affected. 

Yes, you can assume snake_case in the paper for every variable.

**Comment by g0ulash** [comment]
Note @MKaptein for the paper; this also means that the scripts in the defaults will be called get_context.py, get_action.py, get_reward.py, set_reward.py from now on. I will adapt this with each default issue.

**Comment by MKaptein** [comment]
Yes!

Verstuurd vanaf mijn iPhone

**Comment by g0ulash** [comment]
I guess this can be closed now?  @MKaptein @robinvanemden
