### ISSUE TITLE
Nicer error handling for not logged in

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#61]
Hi

If I call http://strm.mnds.org:7070/eval/121e3e0aeb/simulate?N=100&log_stats=False&verbose=False

for an existing experiment, but straight from the browser, I get a "failed to open page"; I suspect this is because I am not logged in (correct?). If so, it would be nicer to give feedback that this is the case instead of "failed to open"

**Comment by g0ulash** [comment]
I suspect that is due to the fact that you login via the front-end and the use the back-end not via the front-end, creating a CORS/header/origin conflict. If you look in the code for the simulation handler, you can see

```
            raise ExceptionHandler(reason="Could not validate user.", status_code=401)
```

And this exception is raised when you're not logged in.

**Comment by MKaptein** [comment]
Well,

Whatever the cause is, a browser call to

http://strm.mnds.org:7070/eval/121e3e0aeb/simulate?N=150&log_stats=False&verbose=False&seed=1271246 <http://strm.mnds.org:7070/eval/121e3e0aeb/simulate?N=150&log_stats=False&verbose=False&seed=1271246>

does not give a nice response. I think it should, so this should be changed.

**Comment by robinvanemden** [comment]
This does indeed have to do with not being logged in, and unset CORS headers. 

More specifically, the client needs to send some info headers to tell where its from, and if one of these is missing (the origin header), the server does not like this. It sort of chokes on the request.

This seems to happen (as far as I can deduce from the error log) because our code tries to set the origin header based on the client's info like so:

`self.set_header("Access-Control-Allow-Origin", self.request.headers.get('Origin'))`

No origin, means self.request.headers.get('Origin') evaluates to "None".

At that point, the server gives up for this particular request.

So we need to either (and/or):

1. Catch the None origin
2. Replace it with a placeholder
3. Throw an error that does get to the client that requested the resource
