### ISSUE TITLE
Investigation of latencies experiment endpoint calls

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#71]
When load testing our experiment related endpoints, even a basic load (rate limited to 100 non-concurrent calls per second) seems to cause huge latencies.

Below an overview of my efforts to pointpoint the origin of this 5 to 7 second latency on all experiment related calls.

#### Focus and load test

I focused on load testing a basic call to the getaction endpoint, with the intention to see if I might be able to get the latency down by commenting out parts of the code.

The load test itself consisted of a wrk process doing 100 calls per second max, non-concurrently, on a clean quad core 16gb Linux virtual server, optimized for StreamingBandit.

#### Basic call

I decided to start out with a minimal getaction function, commenting out almost everything, just returning an empty json string:

	class ActionHandler(tornado.web.RequestHandler):
		   
	    def get(self, exp_id):

		...

		key = self.get_argument("key", default = False)
		context = json.loads(self.get_argument("context", default = "{}"))  

		if not key:
		    raise ExceptionHandler(reason = "Key not supplied.", status_code = 400)		

		self.write("{}")

		...

This results in a nice latency of about 5 milliseconds.    

Python is working, but not too hard, Python single CPU use is at 20%. CPU and memory use of all other processes together not more then 5%.

Mean    =        5.098, StdDeviation   =        0.788

#### Adding initialization of Experiment to the equation

Then I add the line where we initialize an Experiment:

	class ActionHandler(tornado.web.RequestHandler):
		   
	    def get(self, exp_id):

		...

		key = self.get_argument("key", default = False)
		context = json.loads(self.get_argument("context", default = "{}"))  

		__EXP__ = Experiment(exp_id, key)  <--------------------------------------added this line

		if not key:
		    raise ExceptionHandler(reason = "Key not supplied.", status_code = 400)
		
		self.write("{}")

		...

This makes a huge difference!

Mean    =     7094.790, StdDeviation   =     1365.461

The mean latency jumps to 7100 ms!

Python is really working now. Python single CPU use is at 98 to 100%.  CPU and memory use of all other processes together not more then 5%.

By the way, the Python CPU should not be a problem for mongodb and redis themselves, as they can make use of the three CPU's and copious amounts of ram on the testing server.

Also, both Redis and MongoDB themselves seem to hardly break a sweat no matter how heavy we tax StreamingBandit.

####  On to the initialization of Experiment in experiment.py 

So lets see what happens on initialization of an Experiment, in  /core/experiment.py:

    def __init__(self, exp_id, key = "notUsedForLoopBack"):
        self.db = Database()
        self.mongo_db = MongoLog()
        self.advice_db = Advice()
        self.exp_id = exp_id   # sets the experimentID
        self.properties = self.db.get_one_experiment(self.exp_id)
        self.key = key
        self.valid = False     # should be taken from Redis

That's all mainly database initialization. But which line is the main culprit?

####  Mongo

Lets first see what happens when we comment out the mongo related lines, `self.mongo_db = MongoLog()` and `self.advice_db = Advice()`

Mean    =        9.549, StdDeviation   =        2.960

Wow, that helps, back down to 10ms! 

On some further testing, each line,  `self.mongo_db = MongoLog()` and `self.advice_db = Advice()`, attributes 3000+ ms

####  Redis 

Now lets also comment out the redis related lines,  `self.db = Database()`  and `self.properties = self.db.get_one_experiment(self.exp_id)`:

Mean    =        4.971, StdDeviation   =        0.560

That makes sense, now were back to about 5ms.

####  Mongo C extension

To see if another version of Pymongo might help, I installed the latest Pymongo version, 3.6 beta, and its C extension. No difference. Mongo optimization: no difference. Server level optimization: no difference. 

####  Mongo code

Conclusion: we need to make changes to / refactor our MongoDB related code.

**Comment by g0ulash** [comment]
Nice work. I think we can probably solve this by incorporating Motor:

https://motor.readthedocs.io/en/stable/tutorial-tornado.html

**Comment by g0ulash** [comment]
Alright, so I've been digging into this a "incorporating Motor" a little bit. First of all, it turns out that we don't really need Motor instead of PyMongo (YAY!), since we do not use Tornado async (yet). However, the Motor tutorial suggests a really nice solution. This is to only instantiate a MotorClient object once, in the app.py file. And this will, in our case, go as follows:

```
...
# Instantiate DB clients
redis_server = Redis(settings['redis_ip'], settings['redis_port'], decode_responses = True)
mongo_client = MongoClient(settings['mongo_ip'], settings['mongo_port'])

tornadoConfig = dict({
    "template_path": os.path.join(os.path.dirname(__file__),"templates"),
    "debug": True,   # Should get from config?
    "cookie_secret":"12",
    "default_handler_class":basehandler.BaseHandler,
    "redis_server" : redis_server,
    "mongo_client" : mongo_client
})

application = tornado.web.Application(urls,**tornadoConfig)
...
```

The idea then is that in de Handler classes, we can contact the clients as follows:

```
mongo_client = self.settings['mongo_client']
```

However, one problem arises. Since we have separated our Experiment and Database classes from all Handler classes, we can not easily do:

```
class Database:
    """ This database is written in Redis. If other types of database are used,
    they should at least contain the same functions and functionality as the
    functions in this class.
    """
    def __init__(self):
        self.r_server = self.settings['redis_server']
...
```

One idea that might come to mind is to pass the settings in the parameters when initializing the Database class, like so:

```
class Database:
    """ This database is written in Redis. If other types of database are used,
    they should at least contain the same functions and functionality as the
    functions in this class.
    """
    def __init__(self, settings):
        self.r_server = settings['redis_server']
...
```

Then in the Experiment class we would do something like so:

```
class Experiment():
    """ Class that organizes experiments.
    
    :var int exp_id: The exp_id that is tied to the experiment and the \
    database.
    :var string key: The key that is tied to the experiment, to validate \
    the user.
    """
    def __init__(self, exp_id, key = "notUsedForLoopBack", settings):
        self.settings = settings
        self.db = Database(self.settings)
        self.mongo_db = MongoLog(self.settings)
        self.advice_db = Advice(self.settings)
...
```

And then each Handler that uses the Experiment class, will then initialize an Experiment like so:

```
exp  = Experiment(exp_id, key, self.settings)
```

This would be a okay-ish solution in my opinion - I am still not completely satisfied with this, but I think this it the most optimal way.

**However**, the real problem starts now! Remember that we enable users to create an Experiment inside the code that they create themselves? One example is our default for the Nested experiment, where we do:

```
...
# Run the e-first experiment
if choice == 0:
    exp_nested = Experiment(exp_id = id1)
    self.action = exp_nested.run_action_code(context = {})
...
```

Now, if we adopt the previously suggested solution, every user has to do the following:

```
...
# Run the e-first experiment
if choice == 0:
    exp_nested = Experiment(exp_id = id1, settings)
    self.action = exp_nested.run_action_code(context = {})
...
```

And I don't think that this is a viable solution at all! Well, I thought of another option, and this is to create a ```init_nested_experiment``` function, which automatically passes the settings. That would look something like:

```
...
def init_nested_experiment(self, exp_id):
    return Experiment(exp_id = exp_id, settings = self.settings)
...
```

This will result in the eventual use like so:

```
...
# Run the e-first experiment
if choice == 0:
    exp_nested = self.init_nested_experiment(exp_id = id1)
    self.action = exp_nested.run_action_code(context = {})
...
```

This would be my proposal to scale the performance of StreamingBandit. If we adopt this, we have to change the default code and the code in the paper of course, but that won't be the end of the world. What do you guys think?

**Comment by MKaptein** [comment]
Hey,

First, great digging!

Just reading this quickly your proposed solution (if I understand it well just a single instantiation of the mongo_client), seems good (I guess this is also in line with Robin’s earlier ideas? Or am I mixing things up?)

I guess that would ultimately require passing the instantiated object (not the settings themselves, but perhaps I don’t understand your example fully). So yes, that’s what we should do.

For the new experiment; instead of adding a separate init_new_experiment method, can we not just add this to the constructor (e.g., __init__), or is that too simple?

In any case, great digging, and yes, I think we should do something in this direction to prevent redundant instances of the mongo connection(s)

Cheers,

Maurits

**Comment by g0ulash** [comment]
Yes, this will result in a single instance of the MongoClient.

> For the new experiment; instead of adding a separate init_new_experiment method, can we not just add this to the constructor (e.g., __init__), or is that too simple?

I'm not sure what you be with adding this to the constructor? We pass the settings to the constructor when creating a new Experiment object, but when we create a nested Experiment object inside the user created scripts, we have to pass the settings to that Experiment as well. Or do you mean something else?

**Comment by MKaptein** [comment]
Hmmm… 

So, why do you pass the settings? I can see how you would pass the object itself, but the settings in the config file can just be retrieved anew within the experiment class no? In my perception such setting are pretty much like global variables (but, let’s see how Robin sees this).

**Comment by g0ulash** [comment]
You might be right. I'll look into how to pass this as a global variable, not sure how that scoping works, but I'll check that.

**Comment by g0ulash** [comment]
This problem is fixed in e4db135. I added the tornado_config to the builtins module and then the settings become universally available. I don't need to pass any settings onto any init's anymore! Turned out to be quite easy, hurray! 

@robinvanemden will do the performance test again sometime later.

The following link turned out to be very helpful:

https://stackoverflow.com/questions/15959534/python-visibility-of-global-variables-in-imported-modules

**Comment by MKaptein** [comment]
Awesome, you ended up solving it! Very curious how much it helps!

**Comment by robinvanemden** [comment]
This helps *a lot*! During load-testing, I found we do still need to set default PoolSize min and max values on MongoClient's instantiation, like so:

`mongo_client = MongoClient(settings['mongo_ip'], settings['mongo_port'], maxPoolSize=1000, minPoolSize=500)`

Optimal PoolSize values probably depends on the available system resources, but this setting seems to work nicely on our test-bed - and should be an ok default.

On to our benchmark - as you remember, the latency of basic Tornado (T) calls versus StreamingBandit (SB) calls were in the range of 6ms versus 6500ms. 

Now, when we limit constant throughput to R=100 calls per second, we are down to T = 6ms, versus SB (empty getaction) = 7.5ms. Yay :D 

That means we can now actually load-test relevant limits and bottlenecks, and see where we may optimize SB further in the future.

As can be seen in the chart below, a throughput of about R=300 (empty getaction) calls per second begins to choke SB due to high CPU (100%) usage. We may be able to push this CPU usage down by pre-compiling our experiment's code - now we compile this code again and again when we call on exec repeatedly. Still, our current upper limit of 300 calls per second already seems respectable to me.

The same goes for the difference between empty get calls versus AB get/set calls R=100 - the AB test quadruples the latency - not bad, I gather, but possibly optimizable with pre-compilation?

![benchmarks](https://user-images.githubusercontent.com/95014/31992591-fce0bc02-b97a-11e7-8f77-cd941779d47d.png)

Summary: we now have a well behaved SB server that should be able to handle a healthy workload without choking. And we have pathways to testing and optimizing our system further in the future. 

Also, I now have to rewrite our performance section :)

**Comment by MKaptein** [comment]
Hi,

This is awesome!

And I would say enough for the JSS submission; we can describe that pre-compiling in the discussion section, but at least now its quite clear that it is a competitive REST application in terms of speed and throughput. This should be sufficient for most people; those that want to do commercial extremely large size applications probably have the knowledge to scale it even further but we don’t need to focus there.

Again, super awesome work!

Maurits

**Comment by g0ulash** [comment]
This sounds very promising. Indeed we can optimize it further in another release, later on. For now I'll close this issue.
