### ISSUE TITLE
delayed reward

### ISSUE THREAD

**Issue by chanansh** [MKaptein/streamingbandit#77]
does it support reward which accumulates over time? (e.g. for each time t' > t reward can be associated to action in time t).
does it support batch MAB? (multiple decision at each step, e.g. budget?)

**Comment by matanox** [comment]
I think that according to the associated paper, technically this can be
done. Convergence will be slower of course, the more time passes (more
turns are made) between a recommendation being applied to the world and the
time feedback is received / decided for it. Looks like this library is a
fair fit for running experiments on this and/or calibrate a threshold
duration for default feedback. When consulting on this in the Vowpal Wabbit
mailing list, the reply was that there isn't sufficient theory for setting
an optimal threshold, but this may be (in my optimisitc view) determined by
experimentation (or analysis) over one's simulated / typical data, and/or
by following recent published works like https://arxiv.org/abs/1807.02089.

For multiple decisions in each step, I assume you mean interrelated
decisions competing on the same budget. Maybe this can be cast and reduced
into a different formulation that fits the vanilla bandits scenario? or
consult this lineage of publications:
http://proceedings.mlr.press/v49/agrawal16.pdf.

I think streamingbandit's offline evaluation feature would help a little
with experiments, even though its performance may be (?!) too pythonic for
production.

Either way, non-stationarity may be a challenge so careful monitoring
should be set up even if initial success is accomplished.

**Comment by MKaptein** [comment]
Yes, both can be facilitated; as SB allows you to implement custom policies, both of these should not be too hard to implement.

**Comment by chanansh** [comment]
But these (delay and batch) are properties of the environment, not the
policy.
How is this compares to gym?

**Comment by MKaptein** [comment]
Hi Hanan,

It would be nice to get some more background on your objectives for me to properly think along. Yes, (e.g.,) batched updates are part of the environment, but the way I tink of it the policy still needs to “accommodate”. I was merely thinking that it is relatively easy in SB to, in the decision step op a policy (see https://arxiv.org/abs/1602.06700 for details) generate m future actions as opposed to generating 1 (for a batch of size m). Similarly, updating the policy (i.e., updating what we call \theta throughout the manuscript) can easily be done by a set of m actions and rewards simultaneously. This way you would be able to deal with batch MAB. Here, I was thinking of a usage of SB in the “real world”, and hence you would not implement the environment in SB. If you do want to (e.g.,) run a simulation and thus define the environment yourself, SB does provide (limited) functionality to do so, and since each step of the process can be altered at will it should still be totally possible. However, for simulations perhaps our [R] package contextual is more useful: https://github.com/Nth-iteration-labs/contextual

I do not know gym (other than the place where people work up a sweat, which I guess is not what you are referring to). I am happy to help, but please do provide some more details to make this meaningful.

Maurits

**Comment by chanansh** [comment]
I am interesting in budget allocation for performance marketing user acquisition. I need to do decide how to spread budget to maximize future reward which accumulates over time.

**Comment by chanansh** [comment]
And I was referring to https://gym.openai.com/

**Comment by robinvanemden** [comment]
Hi Hanan,

So, if I understand correctly, you are seeking to evaluate, and then maybe implement a contextual multi-armed bandit policy with budget constraints? I believe such problems are generally known as contextual bandits with knapsacks or resourceful contextual bandits?

The first step would then be to decide upon the policy or algorithm you'd want to implement, some inspiration from the literature on this subject:

- https://papers.nips.cc/paper/6292-linear-contextual-bandits-with-knapsacks.pdf
- http://proceedings.mlr.press/v49/agrawal16.pdf
- https://www.ijcai.org/Proceedings/16/Papers/315.pdf

Next, I would implement your policy (potentially including an elegant way to handle delayed rewards) in our R package [contextual](https://github.com/Nth-iteration-labs/contextual) by subclassing contextual's Policy superclass. To support the generation of delayed rewards, you would also need to implement a custom Bandit subclass. Our paper [on Arxiv](https://arxiv.org/pdf/1811.01926.pdf) delineates how you might go about this. See also the package's [source code](https://github.com/Nth-iteration-labs/contextual/tree/master/R) for Bandit and Policy subclass examples.

Such an evaluation of your Policy could also be done with the AI Gym - but the AI Gym is a general purpose reinforcement learning evaluation tool, where [contextual](https://github.com/Nth-iteration-labs/contextual) is designed and optimized for Bandit policy evaluation.

Then, if you are content with your Policy, the next step would be to convert it to Python, add it to your running StreamingBandit instance and start it allocating resources.

Another option would be to evaluate your contextual policy directly in StreamingBandit. Our [Arxiv](https://arxiv.org/abs/1602.06700)  paper should point you in the right direction on how you might go about this. However, where StreamingBandit has been optimized for running live bandit policies and adaptable policy experiments on streaming data, [contextual](https://github.com/Nth-iteration-labs/contextual) has been designed for the fast and efficient parallelized evaluation of new and existing bandit policies on either synthetic or offline data sets.

Anyway, regardless of how you would choose to move forward, I see no practical problems in the implementation of resourceful contextual bandits with delayed feedback in any of the suggested frameworks. I expect it will take you some research and development time though, of course.

Also, we welcome new policy and bandit implementations in (or making use of) either of our packages - any contribution is always more than welcome!
