### ISSUE TITLE
Create sustainable fix for hotfix in PR #83

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#84]
See https://github.com/Nth-iteration-labs/streamingbandit/pull/83 for more details.

**Comment by Dascienz** [comment]
Hey @g0ulash, I think I figured it out. Fortunately the problem doesn't seem to be the self object, but the fact that we're passing mutable objects as default arguments in the class methods. In general, this can lead to all sorts of evil problems because when the default object is mutated within the function, the argument itself also gets mutated. I'll push a much safer fix to avoid this sort of nasty issue in the future.

EDIT: [pull-request](https://github.com/Nth-iteration-labs/streamingbandit/pull/86)

**Comment by g0ulash** [comment]
Great, thanks for finding it!
